### PR TITLE
Added remove tag option

### PR DESCRIPTION
**Pull request by mythodeia**
now you can tap each tag and remove it

### CODE REVIEW

**Comment by zsk425** [comment]
Thanks for your PR.But In your commit,there is a mistake.
I will add some new methods today.

**Comment by mythodeia** [comment]
@zsk425 whats the error? it seems to be working fine though

**Comment by zsk425** [comment]
@mythodeia 
Look at the parameter type of removeTag:,one is SKTag and the other is SKTagButton.

**Comment by mythodeia** [comment]
@zsk425 thanks for pointing that out. i fixed it in my repo. When you push your changes i will update my own.
thanks again

**Comment by zsk425** [comment]
@mythodeia :-D

**Pull request closed without merging**
